version: '3'
services:
  webhook-server:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - C:/Users/davle/Dropbox (Personal)/Jobs 2024:/app/Jobs 2024
    env_file:
      - .env
    command: flask run --host=0.0.0.0 --port=5000
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:5000')"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  localtunnel:
    image: efrecon/localtunnel
    command: --port 5000 --local-host webhook-server --subdomain leatherjobsearch
    restart: unless-stopped
    depends_on:
      - webhook-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge